title: "CallMeSoul"
subTitle: "Front-end developer"
logo: "/images/logo.svg"
favicon: "/images/icon.png"

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  - { name: 首页, description: Home Page, link: /, icon: home }
  - { name: 归档, description: Archive Page, link: /archives/, icon: archives }
  - { name: 目录, description: Archive Page, link: /categories/, icon: category }
  - { name: 关于我, description: About Me, link: /about/, icon: about }


musics:
  - { name: '说好不哭', singer: '周杰伦', url: 'https://callmesoul-blog.oss-cn-shenzhen.aliyuncs.com/music/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E8%AF%B4%E5%A5%BD%E4%B8%8D%E5%93%AD.mp3'}
  - { name: '爱在西元前', singer: '周杰伦', url: 'https://callmesoul-blog.oss-cn-shenzhen.aliyuncs.com/music/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E7%88%B1%E5%9C%A8%E8%A5%BF%E5%85%83%E5%89%8D%20%5Bmqms2%5D.mp3'}
  - { name: '龙拳', singer: '周杰伦', url: 'https://callmesoul-blog.oss-cn-shenzhen.aliyuncs.com/music/%E5%91%A8%E6%9D%B0%E4%BC%A6%20-%20%E9%BE%99%E6%8B%B3%20%5Bmqms2%5D.mp3'}


# 网站统计
statistics:
  # 百度统计
  baidu: f4e4f3d9d2532faa71e451f2ab41cbb6

# Social media
# best four
social:
  weibo: https://weibo.com/tellmesoul/home?wvr=5
  GitHub: https://github.com/callmesoul
  Dribbble: ''
#  Behance: ''
#  Facebook: ''
#  twitter: ''
#  wechat: ''
#  zhihu: ''
#  qq: ''

# Custom footer
mail: callmesoul@foxmail.com
copyright: 2019 CallMeSoul
beian: 粤ICP备15053557号


gitalk:
  clientID: 85810192d72d7f763a9a
  clientSecret: e9867192041e53ad9f4581db6e50bbe7373a090d
  repo: myblog
  owner: callmesoul
  admin: callmesoul
  distractionFreeMode: false


  # Pagination
## Set per_page to 0 to disable pagination


highlight:
  enable: false
prismjs:
  enable: false

